service: tygr-dev
image: tygrdotdev/tygr-dev

servers:
  - 188.245.88.23

env:
  secret:
    - NEXT_PUBLIC_CMS_URL
    - LASTFM_USER
    - LASTFM_API_KEY
    - SPOTIFY_CLIENT_ID
    - SPOTIFY_CLIENT_SECRET
    - SPOTIFY_REFRESH_TOKEN
    - KAMAL_REGISTRY_PASSWORD

proxy: 
  ssl: true
  host: tygr.dev
  app_port: 3000
  healthcheck:
    path: /
    interval: 5

registry:
  server: ghcr.io
  username: tygrdotdev
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: .

asset_path: /app/.next